import Head from 'next/head'
import { NextPage } from 'next'
import { Fragment } from 'react'
import { useTypedSelector } from '../hooks/useTypedSelector';

const HomePage: NextPage = () => {
    const { loggedIn } = useTypedSelector((state) => state.ui);
    let greeTingText = 'Welcome, нажмите LOGIN'
    
    if(loggedIn) {
        greeTingText = 'Просто добавьте то что не хотите забыть'
    }
    
    return (
        <Fragment>
            <Head>
                <title>WishList</title>
                <meta name="All you need, just wish" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h1>{greeTingText}</h1>
            </main>
        </Fragment>
    );
};

export default HomePage
