import { NextPage } from 'next'
import Head from 'next/head'
import { Fragment } from 'react';

const HomePage: NextPage = () => {
    return (
        <Fragment>
            <Head>
                <title>WishList</title>
                <meta name="All you need, just wish" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h2>Welcome to the internet, take a look around....</h2>
            </main>
        </Fragment>
    );
};

export default HomePage
